basepath = ".."
locales = [
    "af",
    "ar",
    "ast",
    "be",
    "bg",
    "br",
    "ca",
    "cak",
    "cs",
    "cy",
    "da",
    "de",
    "dsb",
    "el",
    "en-CA",
    "en-GB",
    "es-AR",
    "es-ES",
    "es-MX",
    "et",
    "eu",
    "fi",
    "fr",
    "fy-NL",
    "ga-IE",
    "gd",
    "gl",
    "he",
    "hr",
    "hsb",
    "hu",
    "hy-AM",
    "id",
    "is",
    "it",
    "ja",
    "ja-JP-mac",
    "ka",
    "kab",
    "kk",
    "ko",
    "lv",
    "lt",
    "mk",
    "ms",
    "nb-NO",
    "nl",
    "nn-NO",
    "pa-IN",
    "pl",
    "pt-BR",
    "pt-PT",
    "rm",
    "ro",
    "ru",
    "sk",
    "sl",
    "sq",
    "sr",
    "sv-SE",
    "th",
    "tr",
    "uk",
    "uz",
    "vi",
    "zh-CN",
    "zh-TW",
]
paths = [
    { reference = "mail/**", l10n = "{l}mail/**" },
    { reference = "chat/**", l10n = "{l}chat/**" },
    { reference = "mail/branding/thunderbird/**", l10n = "{l}mail/branding/thunderbird/**" },
    { reference = "mail/branding/tb_beta/**", l10n = "{l}mail/branding/tb_beta/**" },
]
includes = [
    { path = "_configs/calendar.toml" },
]

[env]
l = "{l10n_base}/{locale}/"
mozilla = ".."

[[filters]]
path = [
    "{l}mail/all-l10n.js",
]
action = "ignore"
